name: UAITO AI Assistant

on:
  issues:
    types: [opened]

jobs:
  run-uaito-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Enable Corepack and set up Yarn
        run: |
          corepack enable
          yarn --version

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ./.npmrc

        env:
          NPM_TOKEN: ${{ env.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build packages
        run: yarn build

      - name: Run UAITO GitHub Action
        run: npx uaito-github-action
        env:
          INPUT_GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_ALLOWED-USER: 'elribonazo'
          INPUT_LLM-PROVIDER: 'OpenAI' # Or Anthropic, Google, etc.
          INPUT_LLM-API-KEY: ${{ secrets.LLM_API_KEY }}
          INPUT_MODEL: 'gpt-4' # Optional, defaults to a good model for the provider
