name: UAITO AI Assistant

on:
  issues:
    types: [opened, edited]

jobs:
  run-uaito-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run UAITO GitHub Action
        run: npx @uaito/github-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-user: 'elribonazo'
          llm-provider: 'OpenAI' # Or Anthropic, Google, etc.
          llm-api-key: ${{ secrets.LLM_API_KEY }}